version: "3.2"
services:
  reverse-proxy:
    image: traefik:2.5
    command: --api.insecure=true --providers.docker=true --entrypoints.web.address=:80
    ports:
      - 8080:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongodb:
    image: "bitnami/mongodb:latest"
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data:/bitnami"

  backend:
    image: "ghcr.io/scicatproject/backend-next:latest"
    # NOTE: This sleep is waiting for mongodb to start. Not the nisest solution but it works for now. Improvemet will be to include the wait-for-it.sh script while building the backend container so we can execute it here. Something similar like this one: https://github.com/SciCatProject/scichat-loopback/blob/master/CI/ESS/Dockerfile.e2e#L11
    command: sh -c "
      sleep 5 &&
      node dist/main"
    ports:
      - 3000:3000
    volumes:
      - "./CI/ESS/e2e/.env.backend-next:/home/node/app/.env"
    depends_on:
      - mongodb
      - scichat-loopback
    labels:
      - "traefik.http.routers.backend.rule=PathPrefix(`/api/v3`, `/auth/msad`)"
      - "traefik.http.routers.backend.entrypoints=web"
volumes:
  mongodb_data:
    driver: local
